# Generated by Django 5.0.3 on 2024-03-29 08:36

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'db_table': 'account_interest',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('user_image', models.ImageField(blank=True, upload_to=accounts.models.profile_image_file_path)),
                ('username', models.CharField(max_length=256)),
                ('designation', models.CharField(blank=True, max_length=256)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('education1', models.CharField(blank=True, max_length=256)),
                ('education2', models.CharField(blank=True, max_length=256)),
                ('bio', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=256)),
                ('interest', models.ManyToManyField(related_name='interest_in', to='accounts.profile')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'account_profile',
                'ordering': ('first_name', 'last_name'),
            },
        ),
    ]
