# Generated by Django 5.0.3 on 2024-03-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_bio_alter_profile_education1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='interest',
            new_name='interests',
        ),
    ]
