# Generated by Django 5.0.3 on 2024-04-02 08:46

import django.db.models.deletion
import feeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_profile_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to='accounts.profile')),
                ('following', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'db_table': 'account_follow',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('friend_request', 'Friend Request')], max_length=256)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'approved'), ('denied', 'denied')], default='pending', max_length=8)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendrequest', to='accounts.profile')),
                ('requested_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('topic', models.CharField(blank=True, max_length=256)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=feeds.models.group_image_file_path)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.profile')),
                ('interest', models.ManyToManyField(blank=True, related_name='group_interest', to='accounts.interest')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'account_group',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=feeds.models.group_post_image_file_path)),
                ('video', models.FileField(blank=True, upload_to=feeds.models.group_post_video_file_path)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to='accounts.profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post', to='feeds.group')),
            ],
            options={
                'verbose_name': 'Group Post',
                'verbose_name_plural': 'Group Posts',
                'db_table': 'account_grouppost',
                'ordering': ('-created_time', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(blank=True, choices=[('profile', 'Profile'), ('post', 'Post'), ('group', 'Group')], max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('hate_speech', 'Hate Speech'), ('inappropriate_language', 'Inappropriate Language'), ('disrespectful_behavior', 'Disrespectful Behavior'), ('violent_or_threatening_language', 'Violent or Threatening Language'), ('other', 'Other')], max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to='accounts.profile')),
                ('to_whom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'account_report',
                'ordering': ('report_type',),
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=feeds.models.post_image_file_path)),
                ('video', models.FileField(blank=True, upload_to=feeds.models.post_video_file_path)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'User Post',
                'verbose_name_plural': 'User Posts',
                'db_table': 'feeds_userpost',
                'ordering': ('created_by',),
            },
        ),
    ]
