# Generated by Django 5.0.3 on 2024-04-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_userpost_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ('-request_status', 'profile__user__username'), 'verbose_name': 'Friend Request', 'verbose_name_plural': 'Friend Requests'},
        ),
        migrations.AlterModelTable(
            name='follow',
            table='feeds_follow',
        ),
        migrations.AlterModelTable(
            name='friendrequest',
            table='feeds_friendrequest',
        ),
        migrations.AlterModelTable(
            name='group',
            table='feeds_group',
        ),
        migrations.AlterModelTable(
            name='grouppost',
            table='feeds_grouppost',
        ),
        migrations.AlterModelTable(
            name='report',
            table='feeds_report',
        ),
    ]
