# Generated by Django 5.0.3 on 2024-05-13 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_interests'),
        ('feeds', '0004_chatroom_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True)),
                ('liked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('userPost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.userpost')),
            ],
            options={
                'verbose_name': 'Liked post',
                'verbose_name_plural': 'Liked posts',
                'db_table': 'feeds_liked_post',
                'ordering': ('userPost',),
            },
        ),
    ]
